encoding: utf-8
name: Gi-Cheon Kang
url: http://gicheonkang.com
author:
  name: Gi-Cheon Kang
  email: gchnkang@gmail.com
description: I am a Ph.D. student in the Graduate School of AI at Seoul National University, advised by Prof. Byoung-Tak Zhang. My research straddles machine learning, natural language processing, computer vision, and robotics. I'm particularly interested in connecting language with perception and action, enabling machines to understand the semantics of the physical world.
permalink: /posts/:title/
include: ['_pages']
